### ISSUE TITLE
Missing Mind Monitor OSC stream to LSL stream bridge

### ISSUE THREAD

**Issue by PeterGamma** [gisogrimm/osc2lsl#1]
Great to have this program. But I miss an executalbe program, which directly connects the OSC stream of the Muse Headband from Mind Monitor app  to Arnaud Delorme PhD. s Neurofeedbacklab:

https://mind-monitor.com/forums/viewtopic.php?f=15&t=840&start=30

**Comment by PeterGamma** [comment]
It is a pity that this issue is closed. I suppose the Swartz Center of Computational Neuroscience, the Center of Healthy Minds, the Meditation Research Institute of Swami Rama Sadhaka Grama, and the Mediation Research Institute of Switzerland would be very interested in this an example. Maybe another person with good coding skills writes an example which connects OSC to LabStreamingLayer?

**Comment by gisogrimm** [comment]
This project is completely independent.
